version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5001"
    volumes:
      - ./app.py:/app/app.py
    command: python app.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - localnet

networks:
  localnet:
    driver: bridge