apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  labels:
    app: flask-backend
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
  - protocol: TCP
    name: backend
    port: 80
    targetPort: backend