fullnameOverride: "ingress-nginx"
controller:
  name: controller
  enableAnnotationValidations: false
  containerName: controller
  containerPort:
    http: 80
    https: 443
  config:
    log-format-escape-json: "true"
    map-hash-bucket-size: "128"
    server-tokens: "false"
    default-type: "application/octet-stream"
    log-format-upstream: '{"connection": "$connection","connection_requests": "$connection_requests","pid": "$pid","request_id": "$request_id","request_length": "$request_length","remote_addr": "$remote_addr","remote_user": "$remote_user","remote_port": "$remote_port","time": "$time_iso8601","request": "$request","full_path": "$request_uri","args": "$args","downstream_service": "$http_service","status": "$status","body_bytes_sent": "$body_bytes_sent","bytes_sent": "$bytes_sent","http_referer": "$http_referer","http_user_agent": "$http_user_agent","http_x_forwarded_for": "$http_x_forwarded_for","http_host": "$http_host","server_name": "$server_name","request_time": "$request_time","upstream": "$upstream_addr","upstream_connect_time": "$upstream_connect_time","upstream_header_time": "$upstream_header_time","upstream_response_time": "$upstream_response_time","upstream_response_length": "$upstream_response_length","upstream_cache_status": "$upstream_cache_status","method": "$request_method","http_cf_ray": "$http_cf_ray"}'
    allow-snippet-annotations: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  autoscaling:
    enabled: false
  replicaCount: 1
  service:
    enabled: true
    external:
      enabled: true
    type: LoadBalancer
    enableHttp: true
    enableHttps: true
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https