imagePullSecrets: []

fullnameOverride: "metrics-server"

serviceAccount:
  create: true

rbac:
  create: true
  pspEnabled: false

apiService:
  create: true
  annotations: {}
  insecureSkipTLSVerify: true
  caBundle: ""

commonLabels: {}
podLabels: {}
podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

priorityClassName: system-cluster-critical

containerPort: 10250

hostNetwork:
  enabled: false

replicas: 1

updateStrategy: {}

podDisruptionBudget:
  enabled: false

defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

args: []

livenessProbe:
  httpGet:
    path: /livez
    port: https
    scheme: HTTPS
  initialDelaySeconds: 0
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /readyz
    port: https
    scheme: HTTPS
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

service:
  type: ClusterIP
  port: 443
  annotations: {}
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Metrics-server"
    env: "production"

addonResizer:
  enabled: false

metrics:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 200Mi
